services:
  bookhotel:
    image: philipz/bookhotel
    depends_on:
      - camunda
  
  flightbook:
    image: philipz/flightbook
    depends_on:
      - camunda
  
  trainbook:
    image: philipz/trainbook
    depends_on:
      - camunda

  camunda:
    image: philipz/camunda-cockpit-plugins:7.21.0
    container_name: camunda
    ports:
      - 8080:8080
    restart: always
    mem_limit: 1g
